In [1]:
import numpy as np
import pandas as pd

In [5]:
dict_df = pd.read_excel("BIG TIME.xlsx", sheetname=None)
dict_df.keys()

dict_keys(['Storage_wxadj', 'WM Ind', 'Dates', 'Pwr', 'RenGen Index', 'NG Prices', 'Imbalance'])

In [6]:
dict_df['Storage_wxadj']

           Date  Storage(adj wx)   positive= bearish
0    2011-06-19         1.537004  negative = bullish
1    2011-06-20         1.853621                 NaN
2    2011-06-21         1.192188                 NaN
3    2011-06-22         0.246267                 NaN
4    2011-06-23        -1.122011                 NaN
5    2011-06-24        -2.124403                 NaN
6    2011-06-25        -2.472184                 NaN
7    2011-06-26        -2.741732                 NaN
8    2011-06-27        -2.683507                 NaN
9    2011-06-28        -2.178810                 NaN
10   2011-06-29        -1.425220                 NaN
11   2011-06-30        -0.384702                 NaN
12   2011-07-01         0.351009                 NaN
13   2011-07-02         1.390127                 NaN
14   2011-07-03         1.733111                 NaN
15   2011-07-04         1.746256                 NaN
16   2011-07-05         2.744544                 NaN
17   2011-07-06         2.673933                 NaN
18   2011-07-07         1.996022                 NaN
19   2011-07-08         0.753927                 NaN
20   2011-07-09        -0.252141                 NaN
21   2011-07-10        -0.372289                 NaN
22   2011-07-11        -1.369658                 NaN
23   2011-07-12        -2.392026                 NaN
24   2011-07-13        -2.378505                 NaN
25   2011-07-14        -1.176468                 NaN
26   2011-07-15        -0.168705                 NaN
27   2011-07-16         0.051087                 NaN
28   2011-07-17        -0.393581                 NaN
29   2011-07-18        -0.169436                 NaN
...         ...              ...                 ...
2047 2016-12-30        -0.152171                 NaN
2048 2016-12-31        -0.501824                 NaN
2049 2017-01-01         1.198199                 NaN
2050 2017-01-02         3.972557                 NaN
2051 2017-01-03         2.585166                 NaN
2052 2017-01-04         0.596706                 NaN
2053 2017-01-05        -1.560107                 NaN
2054 2017-01-06        -3.220742                 NaN
2055 2017-01-07        -5.465247                 NaN
2056 2017-01-08        -6.209523                 NaN
2057 2017-01-09        -3.345490                 NaN
2058 2017-01-10        -0.781456                 NaN
2059 2017-01-11         1.426758                 NaN
2060 2017-01-12         2.310407                 NaN
2061        NaT              NaN                 NaN
2062        NaT              NaN                 NaN
2063        NaT              NaN                 NaN
2064        NaT              NaN                 NaN
2065        NaT              NaN                 NaN
2066        NaT              NaN                 NaN
2067        NaT              NaN                 NaN
2068        NaT              NaN                 NaN
2069        NaT              NaN                 NaN
2070        NaT              NaN                 NaN
2071        NaT              NaN                 NaN
2072        NaT              NaN                 NaN
2073        NaT              NaN                 NaN
2074        NaT              NaN                 NaN
2075        NaT              NaN                 NaN
2076        NaT         0.000000                 NaN

[2077 rows x 3 columns]